//
//  GoalDetailsScreenInteractor.swift
//  GoalTracker
//
//  Created by Georges on 3/5/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine

final class GoalDetailsScreenInteractor {
    
    let date: Date
    let goalFetching: GoalFetching
    let progressFetching: GoalProgressFetching
    var cancellableSet = Set<AnyCancellable>()

    init(
        date: Date,
        goalFetching: GoalFetching,
        progressFetching: GoalProgressFetching
    ) {
        self.progressFetching = progressFetching
        self.goalFetching = goalFetching
        self.date = date
    }
    
    func startFetching() {
        goalFetching.startFetching()
        progressFetching.startFetching()
    }
    
    func stopFetching() {
        goalFetching.stopFetching()
        progressFetching.stopFetching()
    }
    
}

// MARK: - Extensions -

extension GoalDetailsScreenInteractor: GoalDetailsScreenInteractorInterface {
    var goalPublisher: AnyPublisher<Goal, Never> {
        goalFetching
            .goalsPublisher
            .map({ $0.first })
            .compactMap({ $0 })
            .eraseToAnyPublisher()
    }
    var goalProgressPublisher: AnyPublisher<GoalProgress, Never> {
        progressFetching
            .progressPublisher
            .map({ $0.first })
            .compactMap({ $0 })
            .eraseToAnyPublisher()
    }
    func startFetchingUpdates() {
        self.startFetching()
    }
    func stopFetchingUpdates() {
        self.stopFetching()
    }
}
