//
//  GoalDetailsScreenWireframe.swift
//  GoalTracker
//
//  Created by Georges on 3/5/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class GoalDetailsScreenWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(input: GoalDetailsScreenInput) {
        let moduleViewController = GoalDetailsScreenViewController()
        super.init(viewController: moduleViewController)

        let interactor = GoalDetailsScreenInteractor(
            date: input.date,
            goalFetching: input.goalFetching,
            progressFetching: input.progressFetching
        )
        let presenter = GoalDetailsScreenPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension GoalDetailsScreenWireframe: GoalDetailsScreenWireframeInterface {
}
