//
//  MyGoalsScreenWireframe.swift
//  GoalTracker
//
//  Created by Georges on 3/4/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MyGoalsScreenWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = MyGoalsScreenViewController()
        super.init(viewController: moduleViewController)

        let interactor = MyGoalsScreenInteractor()
        let presenter = MyGoalsScreenPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MyGoalsScreenWireframe: MyGoalsScreenWireframeInterface {
    func routeToGoalDetails(date: Date, goalFetching: GoalFetching, progressFetching: GoalProgressFetching) {
        let input = GoalDetailsScreenInput(
            date: date,
            goalFetching: goalFetching,
            progressFetching: progressFetching
        )
        let wireframe = GoalDetailsScreenWireframe(input: input)
        navigationController?.pushWireframe(wireframe)
    }
}
